Repository codesquad-member-2020/issue-tracker-10, pull requests merged in 2020-06, with the labels that each got.

#3 Feature fe/issue 2
  FE/.gitignore
  FE/client/.gitignore
  FE/client/.prettierrc.json
  FE/client/README.md
  FE/client/craco.config.js
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/public/index.html
  FE/client/src/App.jsx
  FE/client/src/index.jsx
  FE/client/src/serviceWorker.js
  FE/client/src/setupProxy.js
  FE/client/yarn.lock
  FE/package.json
  FE/server/mock/issueInitData.js
  FE/server/package.json
  FE/server/server.js
  FE/yarn.lock
Labels: FE

#6 [FE] Label Component 중간 PR
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/public/index.html
  FE/client/src/App.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/LabelItem.jsx
  FE/client/src/components/issues/label/LabelTopMenu.jsx
  FE/client/src/components/table/Table.jsx
  FE/client/src/index.jsx
  FE/client/src/modules/index.js
  FE/client/src/modules/label/labelAction.js
  FE/client/src/modules/label/labelReducer.js
  FE/client/src/style/CustomStyle.jsx
  FE/client/src/style/GlobalStyle.jsx
  FE/client/yarn.lock
Labels: FE

#9 [FE #8] 테스트용 express server 버그 수정
  FE/server/mock/issueInitData.js
  FE/server/server.js
Labels: FE, bug

#11 [FE #10] Milestones 컴포넌트 스타일
  FE/client/src/App.jsx
  FE/client/src/components/issues/milestones/Milestones.jsx
  FE/client/src/components/issues/milestones/MilestonesEditor.jsx
  FE/client/src/components/issues/milestones/MilestonesItem.jsx
  FE/client/src/components/issues/milestones/MilestonesTopMenu.jsx
  FE/client/src/modules/index.js
  FE/client/src/modules/milestones.js
Labels: FE

#12 [FE] 페어 중간 Merge PR
  FE/client/jsconfig.json
  FE/client/package.json
  FE/client/src/components/issues/label/Create.jsx
  FE/client/src/components/issues/label/Edit.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/LabelItem.jsx
  FE/client/src/style/CustomStyle.jsx
  FE/client/src/style/GlobalStyle.jsx
  FE/client/src/util/util.js
  FE/client/yarn.lock
Labels: FE

#16 [FE #13] 2020-06-10
  FE/client/jsconfig.json
  FE/client/src/App.jsx
  FE/client/src/assets/images/github-logo.png
  FE/client/src/components/header/Header.jsx
  FE/client/src/components/header/HeaderMenuList.jsx
  FE/client/src/components/issues/label/Edit.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/LabelItem.jsx
  FE/client/src/components/issues/milestones/Milestones.jsx
  FE/client/src/components/issues/milestones/MilestonesEditor.jsx
  FE/client/src/components/table/SwitchButtons.jsx
  FE/client/src/components/table/TableHeader.jsx
  FE/client/src/modules/index.js
  FE/client/src/modules/label/labelAction.js
  FE/client/src/modules/labels.js
  FE/client/src/style/CustomStyle.jsx
Labels: FE

#17 [FE #10] Milestone 구현
  FE/client/src/App.jsx
  FE/client/src/components/issues/milestone/Milestone.jsx
  FE/client/src/components/issues/milestone/MilestoneEditor.jsx
  FE/client/src/components/issues/milestone/MilestoneEditorButtons.jsx
  FE/client/src/components/issues/milestone/MilestoneEditorHeader.jsx
  FE/client/src/components/issues/milestone/MilestoneItem.jsx
  FE/client/src/components/issues/milestone/MilestoneItemButtons.jsx
  FE/client/src/components/issues/milestone/MilestoneItemProgress.jsx
  FE/client/src/components/issues/milestone/MilestoneTopMenu.jsx
  FE/client/src/components/issues/milestones/MilestonesItem.jsx
Labels: FE

#19 [FE #18] 로그인 버튼
  FE/client/jsconfig.json
  FE/client/src/App.jsx
  FE/client/src/components/header/Header.jsx
  FE/client/src/components/header/HeaderMenuList.jsx
  FE/client/src/components/issues/Issue.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/milestone/Milestone.jsx
  FE/client/src/components/issues/milestone/MilestoneEditor.jsx
  FE/client/src/components/issues/milestone/MilestoneEditorHeader.jsx
  FE/client/src/components/login/Login.jsx
  FE/client/src/util/util.js
Labels: FE

#21 [FE #20] moment 모듈 추가, 적용
  FE/client/package.json
  FE/client/src/components/issues/milestone/MilestoneItem.jsx
Labels: FE

#22 [FE] Label Component
  FE/client/package.json
  FE/client/src/components/issues/label/Edit.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/LabelEditor.jsx
  FE/client/src/components/issues/label/LabelItem.jsx
  FE/client/src/components/issues/label/labelConstanst.js
  FE/client/src/index.jsx
  FE/client/src/modules/labels.js
  FE/client/src/style/CustomStyle.jsx
  FE/client/src/util/util.js
  FE/client/yarn.lock
Labels: FE

#23 [FE] Label Component
  FE/client/src/assets/images/github-character.jpg
  FE/client/src/components/infoMessage/InfoMessage.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/LabelEditor.jsx
  FE/client/src/components/issues/label/LabelItem.jsx
  FE/client/src/components/issues/label/labelConstanst.js
  FE/client/src/components/issues/label/labelConstant.js
  FE/client/src/modules/labels.js
  FE/client/src/style/CustomStyle.jsx
Labels: FE

#25 [FE] Label , Milestone Component
  FE/client/src/components/infoMessage/InfoMessage.jsx
  FE/client/src/components/issues/label/Label.jsx
  FE/client/src/components/issues/label/labelConstant.js
  FE/client/src/components/issues/milestone/Milestone.jsx
  FE/client/src/components/issues/milestone/milestoneConstant.js
  FE/client/src/components/table/SwitchButtons.jsx
  FE/client/yarn.lock
Labels: FE

#29 [FE #28] redux-thunk 적용, 오타수정
  FE/client/src/components/issues/Issue.jsx
  FE/client/src/index.jsx
  FE/client/src/modules/index.js
  FE/client/src/modules/issues.js
  FE/client/src/modules/labels.js
Labels: FE

#31 [#15] 프로젝트 셋업
  BE/.idea/.gitignore
  BE/.idea/BE.iml
  BE/.idea/misc.xml
  BE/.idea/modules.xml
  BE/.idea/vcs.xml
  BE/HELP.md
  BE/build.gradle
  BE/build/classes/java/main/com/group10/issuemaker/Issue.class
  BE/build/classes/java/main/com/group10/issuemaker/IssueDAO$1.class
  BE/build/classes/java/main/com/group10/issuemaker/IssueDAO.class
  BE/build/classes/java/main/com/group10/issuemaker/IssuemakerApplication.class
  BE/build/classes/java/main/com/group10/issuemaker/Label.class
  BE/build/classes/java/main/com/group10/issuemaker/LabelDAO.class
  BE/build/classes/java/main/com/group10/issuemaker/testController.class
  BE/build/resources/main/application.properties
  BE/build/resources/main/data.sql
  BE/build/resources/main/schema.sql
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/group10/issuemaker/Issue.java
  BE/src/main/java/com/group10/issuemaker/IssueDAO.java
  BE/src/main/java/com/group10/issuemaker/IssuemakerApplication.java
  BE/src/main/java/com/group10/issuemaker/Label.java
  BE/src/main/java/com/group10/issuemaker/LabelDAO.java
  BE/src/main/java/com/group10/issuemaker/testController.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/group10/issuemaker/IssuemakerApplicationTests.java
Labels: BE

#34 [FE] Issues : Create Component
  FE/client/package.json
  FE/client/src/App.jsx
  FE/client/src/assets/images/user-sample-image.jpg
  FE/client/src/components/issues/issuesEditor/GithubPicker.jsx
  FE/client/src/components/issues/issuesEditor/IssuesEditor.jsx
  FE/client/src/components/issues/issuesEditor/MarkdownEditor.jsx
  FE/client/src/components/issues/issuesEditor/TimelineComment.jsx
  FE/client/src/components/issues/issuesEditor/createIssues/CreateIssues.jsx
  FE/client/src/components/issues/issuesEditor/issyesEditorConstant.js
  FE/client/src/style/CustomStyle.jsx
  FE/client/src/style/GlobalStyle.jsx
  FE/client/yarn.lock
Labels: FE

#35 [FE #30] issues 목록 상단 버튼 컴포넌트 스타일 작업
  BE/gradlew
  BE/gradlew.bat
  FE/client/src/components/issues/Issue.jsx
  FE/client/src/components/issues/IssueFilterInput.jsx
  FE/client/src/components/issues/IssueItem.jsx
  FE/client/src/components/issues/IssueTopMenu.jsx
  FE/client/src/components/issues/issueConstant.js
  FE/client/src/components/table/TableHeader.jsx
  FE/client/src/modules/issues.js
  FE/client/src/style/CustomStyle.jsx
Labels: FE

#37 [FE #30] 이슈 목록 화면 스타일
  FE/client/src/components/issues/IssueFilterInput.jsx
  FE/client/src/components/issues/IssueItem.jsx
  FE/client/src/style/GlobalStyle.jsx
  FE/server/mock/issueInitData.js
Labels: FE

#42 [#27] feat: GithubPicker Component에서 PickerModal을 재사용 가능하도록 분류
  FE/client/src/components/issues/PickerModal.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/GithubPicker.jsx
Labels: FE

#44 [FE #30] 이슈 목록 화면 구현
  FE/client/src/components/issues/Issue.jsx
  FE/client/src/components/issues/IssueFilterInput.jsx
  FE/client/src/components/issues/IssueItem.jsx
  FE/client/src/components/issues/IssueTopMenu.jsx
  FE/client/src/components/issues/PickerModal.jsx
  FE/client/src/components/issues/filterList/Assignee.jsx
  FE/client/src/components/issues/filterList/Author.jsx
  FE/client/src/components/issues/filterList/Filters.jsx
  FE/client/src/components/issues/filterList/Labels.jsx
  FE/client/src/components/issues/filterList/Milestones.jsx
Labels: FE

#45 [FE] GithubPicker 기능 수정
  FE/client/src/components/issues/PickerModal.jsx
  FE/client/src/components/issues/issuesEditor/IssuesEditor.jsx
  FE/client/src/components/issues/issuesEditor/TimelineComment.jsx
  FE/client/src/components/issues/issuesEditor/createIssues/CreateIssues.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/GithubPicker.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/colorPicker/ColorListItem.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/colorPicker/ColorModalItem.jsx
  FE/client/src/modules/index.js
  FE/client/src/modules/optionPickers.js
  FE/server/mock/assigneerPickerList.js
  FE/server/mock/issueInitData.js
  FE/server/mock/labelPickerList.js
  FE/server/mock/milestonePickerList.js
  FE/server/server.js
Labels: FE

#63 [#30] 이슈 목록 기능 구현
  FE/client/src/components/issues/IssueFilterInput.jsx
Labels: FE

#68 [FE] GithubPicker Component Modal에서 선택 기능 추가
  FE/client/src/components/issues/issuesEditor/IssuesEditor.jsx
  FE/client/src/components/issues/issuesEditor/createIssues/CreateIssues.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/GithubPicker.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/assignees/AssigneesListItem.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/assignees/AssigneesModalItem.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/colorPicker/ColorListItem.jsx
  FE/client/src/components/issues/issuesEditor/githubPicker/colorPicker/ColorModalItem.jsx
  FE/client/src/modules/createIssue.js
  FE/client/src/modules/detailIssue.js
  FE/client/src/modules/index.js
Labels: FE

#73 [FE #64] API 연동
  FE/client/.gitignore
  FE/client/jsconfig.json
  FE/client/src/components/issues/Issue.jsx
  FE/client/src/components/issues/IssueItem.jsx
  FE/client/src/components/issues/milestone/Milestone.jsx
  FE/client/src/components/issues/milestone/MilestoneEditor.jsx
  FE/client/src/components/issues/milestone/MilestoneItem.jsx
  FE/client/src/components/table/SwitchButtons.jsx
  FE/client/src/constants/url.js
  FE/client/src/modules/createIssue.js
  FE/client/src/modules/issues.js
  FE/client/src/modules/milestones.js
Labels: FE
